### ISSUE TITLE
json sample file link is broken

### ISSUE THREAD

**Issue by alexesca** [chipbaber/apex_textdemo#2]
This link is broken. I would like to see the json data

http://lookup-service-prod.mlb.com/json/named.player_info.bam?sport_code=%27mlb%27&player_id=%27493316

Great video, by the way

https://www.youtube.com/watch?v=kGTdOywjnuo&ab_channel=ChipBaber

**Comment by chipbaber** [comment]
Great catch, looks like MLB pulled down the APIs. I did have 3 sample files in my database, I push them to the repo updated the link and they can be downloaded from https://github.com/chipbaber/apex_textdemo/tree/main/json.

**Comment by chipbaber** [comment]
Thx again!
